# Generated by Django 3.1.3 on 2020-12-01 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('regno', models.IntegerField()),
                ('idea', models.TextField(max_length=500)),
                ('result', models.IntegerField(default=0)),
                ('department', models.CharField(choices=[('cs', 'CS'), ('it', 'IT'), ('ec', 'EC'), ('ee', 'EE'), ('me', 'ME'), ('ce', 'CE')], max_length=10)),
                ('position', models.CharField(max_length=100)),
                ('year', models.DateField(auto_now_add=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candid', to='user_auth.profile')),
            ],
        ),
    ]
