# Generated by Django 3.1.3 on 2020-12-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candi_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
